### ISSUE TITLE
ComposeFormula-Aufgabenbeschreibung "dekomponieren"

### ISSUE THREAD

**Issue by patritzenfeld** [fmidue/flex-tasks#2]
> In der Flex-Version wird LogicTasks.Syntax.ComposeFormula.description aufgerufen. Der dort ausgegebene Beschreibungstext 
 enthält Abschnitte wie https://github.com/fmidue/logic-tasks/blob/163bca49794eed48d4da3eb2849b03f58431e9d1/src/LogicTasks/Syntax/ComposeFormula.hs#L59-L60 und  
 https://github.com/fmidue/logic-tasks/blob/163bca49794eed48d4da3eb2849b03f58431e9d1/src/LogicTasks/Syntax/ComposeFormula.hs#L74-L80

>  Diese Texte anzuzeigen ergibt aber keinen Sinn, wenn darunter dann zwei explizite Eingabefelder für die beiden Formeln 
  angezeigt werden statt eines einzelnen Feldes zur Listeneingabe.

>Also muss die description im logic-tasks Repo irgendwie zerlegt oder parametrisiert werden, damit man sich entscheiden kann, was angezeigt wird (während andererseits bei normaler Autotool-Einbettung natürlich weiter der volle bisherige Text angezeigt werden soll).

>Was ist eine geeignete "API" dafür? Lässt sich das sinnvoll auf eine Weise zerlegen, die wahrscheinlich auch bei anderen Aufgabentypen geeignet sein wird? (Auch für https://github.com/fmidue/ma-patrick-ritzenfeld/issues/23 ist das vielleicht am Rande relevant.)

>Muss vielleicht in der Konfigurationsdatei composeFormula.txt in getTask noch irgendwelcher anderer Text zusätzlich ausgegeben werden, der auf die beiden Eingabefelder verweist und die oben zitierten Eingabehinweise ersetzt?

**Comment by patritzenfeld** [comment]
Bisheriger Ansatz: Einen Bool-Parameter hinzufügen, welcher komplett die Eingabehinweise ausschaltet. In den meisten Fällen ist schon durch die Labels der Eingabefelder klar, was wo einzugeben ist.

Es war bisher noch nicht nötig, zusätzlichen Text anzugeben. Das kann dann aber entweder in Flex-Konfigurationen oder im entsprechenden Repo hinzugefügt werden, falls es einen solchen Fall gibt.

**Comment by jvoigtlaender** [comment]
Ich schlage vor, hier in der Konfiguration etwas in diesem Sinne hinzuzufügen: https://github.com/fmidue/logic-tasks/pull/194/files#r1815203448
