### ISSUE TITLE
String-Liste kann nicht automatisch geparst werden

### ISSUE THREAD

**Issue by patritzenfeld** [fmidue/flex-tasks#24]
Da `String = [Char]` wird eine automatische Erzeugung des Parsers durch das Anti-Pattern verhindert.

https://github.com/fmidue/flex-tasks/blob/91e3a1c156143e4ef04f414510451b2f1231a993/flex-task/src/FlexTask/Generic/Parse.hs#L20-L24

**Comment by jvoigtlaender** [comment]
Brauchen wir denn `String`-Listen? Ließe sich argumentieren, dass mittels `flex-task` konfigurierte Aufgaben dann eben `Text`-Listen nutzen sollen? (Passt das gut oder weniger gut zu Eingaben im Browser, etwa hinsichtlich Verwendung von Unicode-Symbolen durch den Nutzer?)

**Comment by patritzenfeld** [comment]
Eigentlich ist es egal. Ich wollte beides anbieten, da es eventuell lästiges Konvertieren zwischen den Typen abnimmt.  Für Unicode macht es glaube ich keinen Unterschied. Intern ist der Textparser sowieso nur ein Stringparser, der dann wieder in Text konvertiert.
