### ISSUE TITLE
Feedback mit Eingabeformbezug bei manchen Aufgaben optional machen? 

### ISSUE THREAD

**Issue by patritzenfeld** [fmidue/flex-tasks#29]
Z. B. bei Aufgaben mit Listeneingabe, die jetzt via Checkboxen umgesetzt werden:

```
Gewählte Option 1 ist verfügbar?
Ja.

Gewählte Option 2 ist verfügbar?
Ja.

Gewählte Option 5 ist verfügbar?
Ja.
```

Macht bei Checkboxen keinen Sinn, da immer alles verfügbar ist, was man auch anklicken kann.

Könnte man analog zu #2 umsetzen.

**Comment by jvoigtlaender** [comment]
Aber müsste man dafür wirklich etwas im `logic-tasks` Repo machen? Könnte man nicht auch einfach im entsprechenden `-Checkboxes` Aufgabentyp im Autotool-Repo die `partial`-Implementierung auf `pure ()` setzen statt die `partial`-Implementierung des Nicht-Checkboxen Aufgabentypes (bzw. `partialGrade` aus `logic-tasks`) zu verwenden?

**Comment by patritzenfeld** [comment]
Stimmt, in den meisten Fällen sollte das ja auch wirklich nur genau dieses Feedback ausschalten.
