### ISSUE TITLE
Eingabe-Legende in Konzert-Aufgabe

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/flex-tasks#43]
Aus Slack:
> Auch bei der Formeleingabe gibt es vielleicht Diskrepanz? (Zumindest gemäß des Aufabentextes, wo nur bestimmte Symbole genannt werden. Vielleicht wird in Wirklichkeit doch allgemeinere Syntax akzeptiert, da Parser aus `logic-tasks` verwendet.)

Wäre es nicht besser, hier statt https://github.com/fmidue/flex-tasks/blob/86ccca20127cebb1fbe5318c7ad3bc4c70911170/tasks/proplogic.txt#L414-L416 auf in `logic-tasks` zur Verfügung stehende Syntax-Legenden zurückzugreifen?

**Comment by patritzenfeld** [comment]
erledigt. (113f9c88a69579da2372bd2788bc6b81e9460e9a)
